---
# Stop minishift profile, delete minishift profile,
# delete minishift binary files, and kube config

- name: "Stop minishift if running"
  shell: "{{ minishift_bin }} stop --profile {{ profile }}"
  ignore_errors: yes
  when:
    - setup_minishift|bool == true

- name: "Delete minishift profile {{ profile }}"
  shell: "{{ minishift_bin }} delete --profile {{ profile }} --force"
  ignore_errors: yes
  when:
    - setup_minishift|bool == true

- name: "Cleanup files and directories {{ minishift_dest_dir }}"
  file:
    path: "{{ minishift_dest_dir }}/{{ item }}"
    state: absent
  with_items:
    - "minishift"
    - "LICENSE"
    - "README.adoc"
  ignore_errors: yes

- name: "Cleanup certain files in {{ contra_env_setup_dir }}"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ contra_env_setup_dir }}/.yml"
    - "{{ contra_env_setup_dir }}/.yaml"
  ignore_errors: yes

- name: "Cleanup certain files in kube config and minishift profile"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_env.HOME }}/.minishift/profiles/{{ profile }}"
    - "{{ ansible_env.HOME }}/.kube"
  ignore_errors: yes
  when:
    - setup_minishift|bool == true

# Determine if project directory exists
- name: "Is project repository present in {{ project_dir }}"
  stat:
    path: "{{ project_dir }}"
  register: pd_is_found

# Remove project directory
- name: "Cleanup {{ project_dir }}"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ project_dir }}"
  when:
    - pd_is_found.stat.exists
    - force_repo_clone|bool == true
