---
# Install minishift

- name: Query for minishift compressed binary
  shell: curl -s https://github.com/minishift/minishift/releases/{{ minishift_ver }} | grep 'minishift-.*-linux.*' | head -1 | sed 's/.*<a href="\(.*\)" .*/https:\/\/github.com\1/'
  register: get_minishift_bin

- name: "Pull down and extract minishift binary to {{ ansible_env.HOME }}"
  unarchive:
    src: "{{ get_minishift_bin.stdout }}"
    dest: "{{ ansible_env.HOME }}"
    remote_src: yes

- name: Set minishift_src_dir fact
  set_fact:
    minishift_src_dir: "{{ get_minishift_bin.stdout | basename | regex_search(regexp,'\\1') | join(' ') }}"
  vars:
    regexp: '(minishift.*amd64).tgz'

- name: "Create a new {{ minishift_dest_dir }} if it doesn't exist"
  file:
    path: "{{ minishift_dest_dir }}"
    state: directory

- name: "Copy minishift version files to {{ ansible_env.HOME }}/minishift/"
  shell: cp {{ ansible_env.HOME }}/{{ minishift_src_dir }}/* {{ minishift_dest_dir }}/

- name: "Delete {{ ansible_env.HOME }}/{{ minishift_src_dir }}"
  file:
    path: "{{ ansible_env.HOME }}/{{ minishift_src_dir }}"
    state: absent

- import_tasks: set_minishift_path.yml