---
# setup minishift

# Determine if minishift binary exists
- name: "Is minishift binary present in {{ minishift_dest_dir }}"
  stat:
    path: "{{ minishift_dest_dir }}/minishift"
  register: minishift_bin

# Install minishift
- import_tasks: install_minishift_bin.yml
  when: (minishift_bin.stat.exists == false or force_minishift_install|bool == true)

# Set disk size, memory, set Openshift version, skip OpenShift version and release check
- name: "Set minishift disk-size {{ disk_size }}"
  shell: "{{ minishift_dest_dir }}/minishift config set disk-size {{ disk_size }}"

- name: "Set minishift disk-size {{ memory }}"
  shell: "{{ minishift_dest_dir }}/minishift config set memory {{ memory }}"

- name: "Set minishift openshift-version to {{ oc_version }}"
  shell: "{{ minishift_dest_dir }}/minishift config set openshift-version {{ oc_version }}"

- name: "Set minishift skip-check-openshift-version"
  shell: "{{ minishift_dest_dir }}/minishift config set skip-check-openshift-version true"

- name: "Set minishift skip-check-openshift-release"
  shell: "{{ minishift_dest_dir }}/minishift config set skip-check-openshift-release true"

- name: "Pull down the minishift iso"
  get_url:
    url: "{{ minishift_iso }}"
    dest: "{{ minishift_dest_dir }}/minishift.iso"
    timeout: 120

# Check if the minishift profile exists
- name: "Check if the minishift profile exists"
  shell: "{{ minishift_dest_dir }}/minishift status --profile {{ profile }} | head -1 | grep -i 'does not exist'"
  register: minishift_exist
  ignore_errors: yes

# Import_tasks to set_oc_client
- name: "Get OpenShift client binary(oc) version {{ oc_version }}to {{ contra_env_setup_dir }}"
  import_tasks: roles/oc_temps/tasks/set_oc_client.yml

# Initialize minishift
- import_tasks: init_minishift.yml
  when: minishift_exist.stdout != ""
