---
# setup minishift

# Determine if minishift binary exists
- name: "Is minishift binary present in {{ minishift_dest_dir }}"
  stat:
    path: "{{ minishift_bin }}"
  register: minishift_bin_path

# Install minishift
- import_tasks: install_minishift_bin.yml
  when: (minishift_bin_path.stat.exists == false or force_minishift_install|bool == true)

# Set disk size, memory, set Openshift version, skip OpenShift version and release check
- name: "Set minishift disk-size {{ disk_size }}"
  shell: "{{ minishift_bin }} config set disk-size {{ disk_size }}"

- name: "Set minishift memory {{ memory }}"
  shell: "{{ minishift_bin }} config set memory {{ memory }}"

- name: "Set minishift openshift-version to {{ oc_version }}"
  shell: "{{ minishift_bin }} config set openshift-version {{ oc_version }}"

- name: "Set minishift skip-check-openshift-version"
  shell: "{{ minishift_bin }} config set skip-check-openshift-version true"
  when: minishift_version != "v1.12.0"

- name: "Set minishift skip-check-openshift-release"
  shell: "{{ minishift_bin }} config set skip-check-openshift-release true"
  when: minishift_version != "v1.12.0"

- name: "Pull down the minishift iso"
  get_url:
    url: "{{ minishift_iso }}"
    dest: "{{ minishift_dest_dir }}/minishift.iso"
    timeout: 120

# Check if the minishift profile exists
- name: "Check if the minishift profile exists"
  shell: "{{ minishift_bin }} status --profile {{ profile }} | head -1 | grep -i 'does not exist'"
  register: minishift_exist
  ignore_errors: yes

# Import_tasks install_oc_bin
- name: "Get OpenShift client binary(oc) version {{ oc_version }} to {{ contra_env_setup_dir }}"
  import_tasks: "{{ playbook_dir }}/roles/os_temps/tasks/install_oc_bin.yml"

# Initialize minishift
- import_tasks: init_minishift.yml
  when: minishift_exist.stdout != ""
