---
# run roles based on certain params
skip_cleanup: true
skip_prereqs: false
setup_minishift: true
start_minishift: true
setup_containers: true
setup_pipelines: true
setup_sample_pipelines: false
force_minishift_install: false
force_repo_clone: true

# Default location to store contra-env-setup
contra_env_setup_dir: "{{ ansible_env.HOME }}/.contra-env-setup"

## minishift values
# minishift version
minishift_version: v1.12.0

# default location for minishift
minishift_dest_dir: "{{ contra_env_setup_dir }}/minishift"

# default minishift profile name
profile: minishift

# disk and memory size
disk_size: 40gb
memory: 6400mb

# base device size
# for rootfs in pods
basedevice_size: 20G

# minishift iso location
minishift_iso: http://artifacts.ci.centos.org/fedora-atomic/minishift/iso/minishift.iso

# cluster username
username: developer

# cluster password
password: developer

# cluster admin username
admin_username: system

# cluster admin password
admin_password: admin

# project for openshift
project: contra-sample-project

# modify tags on images
modify_tags: true

# tag to use
tag: stable

# modify security context contraints (SCC) to run privileged containers
modify_scc: true

## oc cli vars
# oc version
oc_version: v3.6.1

## Project repo setup

# Project repo
project_repo: https://github.com/CentOS-PaaS-SIG/contra-env-sample-project

# Project directory
project_dir: "{{ contra_env_setup_dir }}/contra-env-sample-project"

# Project repo refspec
project_refspec: '+refs/pull/*:refs/heads/*'

# Project repo branch or sha
project_branch: 'master'

# OpenSift template directory
os_template_dir: "{{ project_dir }}/config/s2i"

# Jenkins pipelines directory
pipeline_dir: "{{ project_dir }}"

## TODO: Get this setup to take a sample project
## Sample pipeline vars used
# enable the sample pipeline
# Note: This will eventually moved to an example project repo)

sample_pipelines:
  - src_loc: "{{ playbook_dir }}/roles/pipeline/templates/contra-sample-pipeline1.xml.j2"
    dest_loc: "{{ contra_env_setup_dir }}/contra-sample-pipeline1/config.xml"
    jenkins_file: "{{ playbook_dir }}/roles/pipeline/files/JenkinsfileContraSample1"

# These are parameters that are passed to setup the containers for the pipeline
PARAMS:
  - key: REPO_URL
    val: "{{ project_repo }}"
  - key: REPO_REF
    val: "{{ project_branch }}"
  - key: ENABLE_VM
    val: false
  - key: VM_IMG_URL
    val: http://artifacts.ci.centos.org/artifacts/fedora-atomic/f26/images/latest-atomic.qcow2
params: []