---
# run roles based on certain params
run_cleanup: false
run_prereqs: true
setup_minishift: true
start_minishift: true
setup_containers: true
setup_pipelines: false
setup_sample_project: false
force_minishift_install: false
force_repo_clone: true

# Default location to store contra-env-setup
contra_env_setup_dir: "{{ ansible_env.HOME }}/.contra-env-setup"

# Docker KVM version
dkvm_version: v0.7.0

## minishift values
# minishift version
minishift_version: v1.12.0

# default location for minishift
minishift_dest_dir: "{{ contra_env_setup_dir }}/minishift"

# default minishift profile name
profile: minishift

# disk and memory size
disk_size: 40gb
memory: 6400mb

# minishift iso location
minishift_iso: http://artifacts.ci.centos.org/fedora-atomic/minishift/iso/minishift.iso

# cluster username
username: developer

# cluster password
password: developer

# cluster admin username
admin_username: system

# cluster admin password
admin_password: admin

# project for openshift
openshift_project: contra-sample-project

# modify tags on images
modify_tags: true

# tag to use
tag: stable

# modify security context contraints (SCC) to run privileged containers
modify_scc: true

## oc cli vars
# oc version
oc_version: v3.6.1

## Project repo setup

# Project repo
project_repo: https://github.com/CentOS-PaaS-SIG/contra-env-sample-project

# Project repo refspec
project_refspec: '+refs/pull/*:refs/heads/*'

# Project repo branch or sha
project_branch: 'master'

# Project directory
project_dir: "{{ contra_env_setup_dir }}/{{ project_repo.split('/')[-1] | replace('.git', '') }}"

# Loaded pipelines directory
loaded_pipelines_dir: "{{ contra_env_setup_dir }}/loaded_pipelines"

# OpenSift template directory
os_template_dir: "config/s2i"

# Jenkins pipelines directory
pipeline_dir: "config/pipelines"
pipeline_dir_orig: "{{ pipeline_dir }}"

# These are parameters that are passed to setup the containers for the pipeline
PARAMS:
  - key: REPO_URL
    val: "{{ project_repo }}"
  - key: REPO_REF
    val: "{{ project_branch }}"
  - key: ENABLE_VM
    val: false
  - key: VM_IMG_URL
    val: http://artifacts.ci.centos.org/artifacts/fedora-atomic/f26/images/latest-atomic.qcow2
params: []

## Sample containers and pipelines

# Sample project repo
sample_project_repo: https://github.com/CentOS-PaaS-SIG/contra-env-sample-project

# Sample Project repo refspec
sample_project_refspec: '+refs/pull/*:refs/heads/*'

# Sample project repo branch or sha
sample_project_branch: 'master'

# Sample project directory
sample_project_dir: "{{ contra_env_setup_dir }}/{{ sample_project_repo.split('/')[-1] | replace('.git', '')}}"

# Sample OpenSift template directory
sample_os_template_dir: "config/s2i"

# Sample Jenkins pipelines directory
sample_pipeline_dir: "config/pipelines"
sample_pipeline_dir_orig: "{{ sample_pipeline_dir }}"

