---
# tasks file for Jenkins pipelines

# Check if Jenkins is running
- name: "Check to see if a Jenkins Master instance is running"
  shell: oc get pods | grep -i 'running' | grep -i 'jenkins' | tail -1 |  awk '{print $1}'
  register: jenkins_running
  ignore_errors: yes

# Create sample pipeline setup_pipelines.yml
- name: "Setup Sample Pipelines"
  import_tasks: setup_pipelines.yml
  when: (setup_sample_project|bool == true and jenkins_running.stdout != "")

# TODO: beyond the sample as we analyze teams we will start to accumlate patterns for pipeline examples
# ex. platform-pipeline
# ex. container-pipeline
# ex. rhv-pipeline
# ex. storage-pipeline
#    |
#    --> gluster-pipeline
#    |
#    --> ceph-pipeline