---
- set_fact:
    params: []

- name: Cleanup any failed containers on the cluster
  shell: "oc get all | egrep 'Failed|Error' | egrep 'builds' | awk '{print $1}' | awk -F'/' '{print $2}' | sed 's/-[0-9+]//g' | xargs -i oc delete bc/{} is/{}"
  ignore_errors: yes

- name: "{{ container_config_name }} :: Get template name from the yaml file"
  shell: oc process -f {{ pipeline_dir }}/config/s2i/{{ template_name }}-buildconfig-template.yaml | jq '.items[1].metadata.labels.template' | sed 's/"//g'
  args:
    chdir: "{{ pipeline_dir }}/config/s2i/"
  register: "template_name_file"

- debug:
    msg: "{{ container_config_name }} :: Template Name in file: {{ template_name_file.stdout }}"

- name: "{{ container_config_name }} :: Get template name from querying the cluster"
  shell: oc get templates | awk '{print $1}' | egrep '^{{ template_name_file.stdout }}$'
  register: "template_name_check"
  ignore_errors: yes

- debug:
    msg: "{{ container_config_name }} :: Template Name from querying the cluster: {{ template_name_check.stdout }}"

- name: "{{ container_config_name }} :: Updating buildconfig {{ template_name }}"
  shell: oc replace -f {{ pipeline_dir }}/config/s2i/{{ template_name }}-buildconfig-template.yaml
  args:
    chdir: "{{ pipeline_dir }}/config/s2i/"
  when: template_name_check.stdout != ""

- name: "{{ container_config_name }} :: Creating buildconfig {{ template_name }}"
  shell: oc create -f {{ pipeline_dir }}/config/s2i/{{ template_name }}-buildconfig-template.yaml
  args:
    chdir: "{{ pipeline_dir }}/config/s2i/"
  when: template_name_check.stdout == ""

# imagestreams
- name: "{{ container_config_name }} :: Get imagestream name from the yaml file"
  shell: oc process -f {{ pipeline_dir }}/config/s2i/{{ template_name }}-buildconfig-template.yaml | jq '.items[0].metadata.name' | sed 's/"//g'
  args:
    chdir: "{{ pipeline_dir }}/config/s2i/"
  register: "image_stream_name_file"

- name: "{{ container_config_name }} :: Get imagestream from querying the cluster"
  shell: oc get imagestream | awk '{print $1}' | egrep '^{{ image_stream_name_file.stdout }}$'
  ignore_errors: yes
  register: "image_stream_name_check"

- debug:
    msg: "{{ container_config_name }} :: Imagestream Name from querying the cluster: {{ image_stream_name_check.stdout }}"

- debug:
    msg: "{{ container_config_name }} :: Imagestream {{ image_stream_name_check.stdout }} already exists"
  when: image_stream_name_check.stdout != ""

# buildconfigs
- name: "{{ container_config_name }} :: Get buildconfig name from the yaml file"
  shell: oc process -f {{ pipeline_dir }}/config/s2i/{{ template_name }}-buildconfig-template.yaml | jq '.items[1].metadata.name' | sed 's/"//g'
  args:
    chdir: "{{ pipeline_dir }}/config/s2i/"
  register: "build_config_name_file"

- name: "{{ container_config_name }} :: Get buildconfig from querying the cluster"
  shell: oc get buildconfig | awk '{print $1}' | egrep '^{{ build_config_name_file.stdout }}$'
  ignore_errors: yes
  register: "build_config_name_check"

- debug:
    msg: "{{ container_config_name }} :: Buildconfig Name from querying the cluster: {{ build_config_name_check.stdout }}"

- debug:
    msg: "{{ container_config_name }} :: Buildconfig {{ build_config_name_check.stdout }} already exists"
  when: build_config_name_check.stdout != ""

- name: "{{ container_config_name }} :: Check if the template being loaded contains the parameter..."
  shell: "oc describe template {{ template_name_file.stdout }} | grep {{ item.key }}"
  register: check_temp_params
  with_items: "{{ PARAMS }}"
  ignore_errors: yes

- set_fact:
    params: "{{ params | default([]) }} + [ '-p {{ item.item.key }}={{ item.item.val }}' ]"
  when: (item.stdout != "" and item.item.val != "")
  with_items: "{{ check_temp_params.results }}"

- set_fact:
    build_success: false

- include: build_new_app.yml
  with_items:
    - 1
    - 2
    - 3
  when: build_success|bool == false

- name: "{{ container_config_name }} :: Imagestream and buildconfig do not exist. Creating..."
  shell: oc new-app {{ template_name_file.stdout }} {{ params | join(" ") }}
  args:
    chdir: "{{ pipeline_dir }}/config"
  when: (image_stream_name_check.stdout == "" and build_config_name_check.stdout == "" and build_success|bool == false)

# Wait container in the pipeline to start building :: FINAL ATTEMPT
- name: "{{ container_config_name }} :: Wait for {{  build_config_name_file.stdout }} to be queued :: FINAL ATTEMPT"
  shell: "oc get builds | grep '{{  build_config_name_file.stdout }}'"
  register: oc_build_result
  until: oc_build_result.stdout.find(" Pending ") == -1
  retries: 6
  delay: 10
  ignore_errors: yes
  when: build_success|bool == false

# Wait container in the pipeline to be finished building :: FINAL ATTEMPT
- name: "{{ container_config_name }} :: Wait for {{  build_config_name_file.stdout }} to be built and marked with latest tag :: FINAL ATTEMPT"
  shell: "oc get builds | grep '{{  build_config_name_file.stdout }}'"
  register: oc_build_result
  until: (oc_build_result.stdout.find(" Running ") == -1 or oc_build_result.stdout.find(" Failed ") != -1)
  retries: 300
  delay: 10
  when: build_success|bool == false

# Cleanup any failed containers
- name: Cleanup any failed containers
  shell: "oc get all | egrep 'Failed|Error' | egrep 'builds' | awk '{print $1}' | awk -F'/' '{print $2}' | sed 's/-[0-9+]//g' | xargs -i oc delete bc/{} is/{}"
  ignore_errors: yes
  when: (build_success|bool == false and oc_build_result is defined and oc_build_result.stdout.find(" Failed ") != -1)

# If oc_build result is defined publish the outcome
- debug:
    msg: "End result of building the container image :: {{ oc_build_result.stdout }}"
  when: oc_build_result.stdout is defined

# Setup tag if container image build successful
- name: Modify tags on images
  shell: "oc get is | awk '{print $2}' | grep -v DOCKER | sed 's/.*5000\\///g' | grep '{{ build_config_name_file.stdout }}' | xargs -i oc tag {}:latest {}:{{ tag }}"
  when: ('modify_tags|bool == true' and build_success|bool == true)