---
# clone the project repo

# Determine if project repo exists
- name: "Is project repository present in {{ project_dir }}"
  stat:
    path: "{{ project_dir }}"
  register: pd_is_found

- name: "Set http.sslVerify false"
  shell: git config --global http.sslVerify false

# git clone project_repo
- name: "checkout the project repo @ {{ project_repo }} to {{ project_dir }}"
  git:
    repo: "{{ project_repo }}"
    dest: "{{ project_dir }}"
    refspec: "{{ project_refspec }}"
    version: "{{ project_branch }}"
    force: yes
  when: ((pd_is_found.stdout is defined and pd_is_found.stdout == "")  or force_repo_clone|bool == true)

# git clone sample_project_repo
- name: "checkout the sample project repo @ {{ sample_project_repo }} to {{ sample_project_dir }}"
  git:
    repo: "{{ sample_project_repo }}"
    dest: "{{ sample_project_dir }}"
    refspec: "{{ sample_project_refspec }}"
    version: "{{ sample_project_branch }}"
    force: yes
  when: (project_repo != sample_project_repo and setup_sample_project|bool == true)