---
# tasks file for create

- name: "Create contra-env-setup directories"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ contra_env_setup_dir }}"
    - "{{ minishift_dest_dir }}"