---
# tasks file for create

- name: "Create contra-env-setup directories"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ contra_env_setup_dir }}"
    - "{{ minishift_dest_dir }}"

- name: "Update os_template_dir based on repo"
  set_fact:
     os_template_dir: "{{ project_dir }}/{{ os_template_dir }}"

- name: "Update pipeline_dir based on repo"
  set_fact:
     pipeline_dir: "{{ project_dir }}/{{ pipeline_dir }}"

- name: "Update sample_os_template_dir based on repo"
  set_fact:
     os_template_dir: "{{ sample_project_dir }}/{{ sample_os_template_dir }}"
  when: setup_sample_pipelines|bool == "true"

- name: "Update sample_pipeline_dir based on repo"
  set_fact:
     pipeline_dir: "{{ sample_project_dir }}/{{ sample_pipeline_dir }}"
  when: setup_sample_pipelines|bool == "true"

# Clone the project_repo and sample_project_repo
- name: "Clone the project repo {{ project_repo }}"
  import_tasks: clone_repos.yml