---
- hosts: '{{ hosts | default("all") }}'
  become: '{{ become | default("no") }}'
  become_user: '{{ become_user | default("root") }}'
  remote_user: '{{ remote_user | default("root") }}'
  gather_facts: '{{ gather_facts | default("yes") }}'
  roles:
    - { role: cleanup, when: skip_cleanup|bool == false }
    - role: create
    - { role: prereqs, when: "skip_prereqs|bool == false and setup_minishift|bool == true" }
    - { role: minishift, when: setup_minishift|bool == true }
    - { role: os_temps, when: setup_containers|bool == true }
    - { role: pipeline, when: setup_pipelines|bool == true }