---
- hosts: '{{ hosts | default("all") }}'
  become: '{{ become | default("no") }}'
  become_user: '{{ become_user | default("root") }}'
  remote_user: '{{ remote_user | default("root") }}'
  gather_facts: '{{ gather_facts | default("yes") }}'
  roles:
    - { role: cleanup, when: skip_cleanup|bool == true }
    - { role: prereqs, when: skip_prereqs|bool == false }
    - { role: minishift, when: setup_minishift|bool == true }
    #- { role: os_cont_temps, when: setup_os_temps|bool == true }
    - role: pipeline