---
- name: "{{ container_config_name }} :: Imagestream and buildconfig do not exist. Creating..."
  shell: "{{ oc_bin }} new-app {{ template_name_files[template_name] }} {{ params | join(' ') }}"
  args:
    chdir: "{{ project_dir }}/config"
  when: (image_stream_name_checks[template_name] == "" and build_config_name_checks[template_name] == "" and build_results[template_name]|bool == false)

# Wait container in the pipeline to start building
- name: "{{ container_config_name }} :: Wait for {{  build_config_name_files[template_name] }} to be queued"
  shell: "{{ oc_bin }} get builds | grep '{{  build_config_name_files[template_name] }}'"
  register: oc_build_result
  until: oc_build_result.stdout.find(" Running ") != -1
  retries: 6
  delay: 10
  ignore_errors: yes
  when: build_results[template_name]|bool == false

