---
# tasks file for os_temps

# Check if the minishift cluster is started if not then start the cluster
- name: "Startup the minishift cluster"
  import_tasks: start_mcluster.yml
  when: (setup_minishift|bool == true or start_minishift|bool == true)

# Import_tasks install_oc_bin
- name: "Get OpenShift client binary(oc) version {{ oc_version }} to {{ contra_env_setup_dir }}"
  import_tasks: install_oc_bin.yml
  when: setup_minishift|bool == false

# Get ip of the cluster unless it was provided
- name: "Get the cluster Server URL for project {{ openshift_project }}"
  shell: "{{ oc_bin }} status | egrep '{{ openshift_project }}.*server' | awk '{print $NF}'"
  register: cluster_ip_register
  when: openshift_cluster_ip == ""

- set_fact:
    cluster_ip: "{{ openshift_cluster_ip }}"
  when: openshift_cluster_ip != ""

- set_fact:
    cluster_ip: "{{ cluster_ip_register.stdout }}"
  when: openshift_cluster_ip == ""

# Login to the cluster for the profile in use
- import_tasks: login_to_cluster.yml

# Create project
- name: "Create project {{ openshift_project }}"
  import_tasks: get_set_project.yml

# Import_tasks jq for querying container config files
- name: "Install jq for querying container config files"
  import_tasks: "{{ playbook_dir }}/roles/prereqs/tasks/install_virtual_reqs.yml"
  when: setup_minishift|bool == true

# setup_containers.yml
- import_tasks: setup_containers.yml
  when: setup_containers|bool == true

# Add security context constraints
- import_tasks: add_scc.yml
  when: modify_scc|bool == true