---
# create/update and add security for containers

- name: "Set the container_config_name to OpenShift s2i templates"
  set_fact:
    container_config_name: "OpenShift s2i templates"

# Use the repo's OpenShift s2i templates as the list to process
- name: "Get OpenShift s2i template names from {{ os_template_path }}"
  find:
    paths: "{{ os_template_path }}"
    patterns: '*.yml,*.yaml'
    contains: 'kind:\s*[\"\'']?Template[\"\'']?'
    recurse: yes
  register: os_templates

- debug:
    msg: "{{ item.path }}"
  with_items: "{{ os_templates.files }}"

- name: "Process the templates"
  template:
    src: "{{ item.path }}"
    dest: "{{ item.path }}.processed"
  with_items: "{{ os_templates.files }}"

# Check that templates are valid
- name: "Check that templates are valid"
  shell: "{{ oc_bin }} process -f {{ item.path }}.processed"
  with_items: "{{ os_templates.files }}"

# Set the total build success
- set_fact:
    total_build_success: false

# Setup project_repo templates and store variables for each template
- name: "Setup project_repo templates and store variables for each template"
  include_tasks: "setup_os_templates.yml template_name={{ item.path }}.processed"
  with_items: "{{ os_templates.files }}"
  when: os_templates.files != ""

# Handle loading of project_repo templates into OpenShift
- name: "Handle loading of project_repo templates into OpenShift"
  include_tasks: "check_os_templates.yml"
  with_sequence: count=4
  when: os_templates.files != ""


