---
## Only run of project_repo != sample_project_repo and setup_sample_project == true
# Check if Jenkins is running
- name: "Check to see if a Jenkins Master instance is running"
  shell: "{{ oc_bin }} get pods | grep -i 'running' | grep -i 'jenkins' | tail -1 |  awk '{print $1}'"
  register: jenkins_running
  ignore_errors: yes

## Only run if Jenkins Master is NOT present
- name: "Get sample Jenkins OpenShift s2i template names from {{ sample_os_template_dir }}/jenkins"
  find:
    paths: "{{ sample_project_dir }}/{{ sample_os_template_dir }}/jenkins"
    patterns: '*.yml,*.yaml'
    recurse: yes
  register: sample_jenkins_os_templates
  when: jenkins_running.stdout == ""

- debug:
    msg: "Sample OpenShift s2i Jenkins master/slave Template: {{ item.path }}"
  with_items: "{{ sample_jenkins_os_templates.files }}"
  when: jenkins_running.stdout == ""

- name: "Process the sample Jenkins templates"
  template:
    src: "{{ item.path }}"
    dest: "{{ item.path }}.processed"
  with_items: "{{ sample_jenkins_os_templates.files }}"
  when: jenkins_running.stdout == ""

# Check that templates are valid
- name: "Check that sample Jenkins templates are valid"
  shell: "{{ oc_bin }} process -f {{ item.path }}.processed"
  with_items: "{{ sample_jenkins_os_templates.files }}"
  when: jenkins_running.stdout == ""

# Load sample_project_repo templates into OpenShift
- include_tasks: "setup_os_templates.yml template_name={{ item.path }}.processed"
  with_items: "{{ sample_jenkins_os_templates.files }}"
  when: jenkins_running.stdout == ""


## Sample project containers besides Jenkins master and slave
- name: "Get sample OpenShift s2i template names from {{ sample_os_template_dir }}/samples"
  find:
    paths: "{{ sample_project_dir }}/{{ sample_os_template_dir }}/samples"
    patterns: '*.yml,*.yaml'
    recurse: yes
  register: sample_os_templates

- debug:
    msg: "Sample OpenShift s2i Template: {{ item.path }}"
  with_items: "{{ sample_os_templates.files }}"

- name: "Process the sample templates"
  template:
    src: "{{ item.path }}"
    dest: "{{ item.path }}.processed"
  with_items: "{{ sample_os_templates.files }}"

# Check that sample templates are valid
- name: "Check that sample templates are valid"
  shell: "{{ oc_bin }} process -f {{ item.path }}.processed"
  with_items: "{{ sample_os_templates.files }}"

# Set PARAMS to the sample ones
- set_fact:
    PARAMS: "{{ SAMPLE_PARAMS }}"
  when: sample_os_templates.files is defined

# Load sample project_repo templates into OpenShift
- include_tasks: "setup_os_templates.yml template_name={{ item.path }}"
  with_items: "{{ sample_os_templates.files }}"
